In [2]:
import pandas as pd
import numpy as np

In [3]:
df= pd.read_csv('full_df_cleaned.csv')

In [4]:
df

,Diagnostic,filename,target_init,Patient Age,Patient Sex,Target,tarstr
0,normal fundus,0_right.jpg,"[1, 0, 0, 0, 0, 0, 0, 0]",69,Female,"[1, 0, 0, 0, 0, 0, 0, 0]",N
1,normal fundus,1_right.jpg,"[1, 0, 0, 0, 0, 0, 0, 0]",57,Male,"[1, 0, 0, 0, 0, 0, 0, 0]",N
2,moderate non proliferative retinopathy,2_right.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",42,Male,"[0, 1, 0, 0, 0, 0, 0, 0]",D
3,mild nonproliferative retinopathy,4_right.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",53,Male,"[0, 1, 0, 0, 0, 0, 0, 0]",D
4,moderate non proliferative retinopathy,5_right.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",50,Female,"[0, 1, 0, 0, 0, 0, 0, 0]",D
...,...,...,...,...,...,...,...
12457,severe nonproliferative retinopathy,4686_left.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",63,Male,"[0, 1, 0, 0, 0, 0, 0, 0]",D
12458,moderate non proliferative retinopathy,4688_left.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",42,Male,"[0, 1, 0, 0, 0, 0, 0, 0]",D
12459,mild nonproliferative retinopathy,4689_left.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",54,Male,"[0, 1, 0, 0, 0, 0, 0, 0]",D
12460,mild nonproliferative retinopathy,4690_left.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",57,Male,"[0, 1, 0, 0, 0, 0, 0, 0]",D
12461,hypertensive retinopathy，age-related macular d...,4784_left.jpg,"[0, 0, 0, 0, 0, 1, 0, 0]",58,Male,"[0, 1, 0, 0, 1, 1, 0, 0]",DAH

In [6]:
df['Target'].head().apply(pd.Series)

                          0
0  [1, 0, 0, 0, 0, 0, 0, 0]
1  [1, 0, 0, 0, 0, 0, 0, 0]
2  [0, 1, 0, 0, 0, 0, 0, 0]
3  [0, 1, 0, 0, 0, 0, 0, 0]
4  [0, 1, 0, 0, 0, 0, 0, 0]